project_id = "vfqqlifvhooefxvvyebm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-inventory-forecast]
verify_jwt = true

[functions.amazon-feed-receiver]
verify_jwt = true

[functions.amazon-sftp-receiver]
verify_jwt = true

[functions.amazon-test-sender]
verify_jwt = true

[functions.generate-export-download]
verify_jwt = true

[functions.generate-ssh-keys]
verify_jwt = true

[functions.get-all-po-data]
verify_jwt = true

[functions.integration-diagnostics]
verify_jwt = true

[functions.process-po-background]
verify_jwt = true

[functions.send-inventory-email]
verify_jwt = true

[functions.sunsky-api]
verify_jwt = false

[functions.vendor-inventory-feed]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.cleanup-old-exports]
verify_jwt = false

[functions.purchase-link-handler]
verify_jwt = false

[functions.fulfill-from-stock]
verify_jwt = true